---
- hosts: "all" # применяем команды ко всем хостам из inventory
  become: true # становимся привилегированным пользователем
  vars_files:
    - vars/usernames.yaml # добавляем переменные
    - vars/users_pass.yaml
  roles:
  - create_user
