# configure selinux
 - name: "Allow anon write access through SELinux"
   ansible.posix.seboolean:
    name: "{{ item }}"
    state: yes
    persistent: yes
   loop:
    - ftpd_anon_write
    - ftpd_use_passive_mode
    - ftpd_full_access
   when: ansible_distribution == "CentOS"
