
  - name: "Permit traffic in default zone for http service"
    ansible.posix.firewalld:
     service: "{{ web_server_port }}"
     permanent: yes
     state: enabled

  - name: "Restart service firewalld"
    ansible.builtin.service:
      name: firewalld
      state: restarted
